### ISSUE TITLE
New pairing is required every time client’s IP changes

### ISSUE THREAD

**Issue by esgie** [jkcoxson/JitStreamer#5]
I have succefuly built and run my own JetStreamer instalce, which I access either directly from my home network or through OpenVPN gateway.
I have succefully paired the device when I was in home. It was warking perfectly fine. But it wasn’t through VPN. Surprisingly, the server insisted that the device wasn’t registered.
The problem is that my local network use dhcp and is assigning my iPad different local IP, than the predefined one assigned to the same iPad by VPN gateway. After taking a look inside database.json and into the code I have found out that not only pairing data (including UDID which itself is enough to identify a specific device…) but also IP address of the client is saved during registration and when he connects again, his IP must be exactly the same, otherwise JitStreamer won’t recognize the device as registered and will keep insist on a new pairing process even if pairing file is absolutely enough valid to identify and communicate with him as expected.
I have worked around by duplicating the entries in database.json for both IPs.
But this is not an ultimate solution - I believe dhcp may aassign absolutely different IP to same device some day so I’d have to duplicate the entry 253 times to cover my local adress space.

In my opinion, there should be a way to disable IP verification - in fact I think it would be desired to remove it at all. First, I think it does not provide any real security (it’s VPN software that is dedicated and focused on identity verification…), but may be a problem for many who don’t matter to hard-bind his mobile devices to static ips… Second, JitStreamer already offers „allowedIps” option in config. If someone wishes to limit pairing to only a single IP, he can easily define a explicit IP address there.

Thanks for great job by the way. A brilliant solution.

**Comment by jkcoxson** [comment]
There is no way to get around IP verification, because that's how the server knows what device has sent the request and therefore what device to launch an app for. This is the only way to ensure an attacker doesn't launch apps on other peoples' devices, and so the sender doesn't have to send other identifying information in their requests. It's designed to be simple for the end user.

JitStreamer was designed to run on a network with static IP assignment. I would go into your router's settings and give your device a static IP.

The allowedIPs option can be left empty and any IP will be allowed. It's there so people can't be dumb and try to register devices behind a NAT.

**Comment by jkcoxson** [comment]
This is something that cannot be replaced, but if you come up with a better idea reopen this issue.
